services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
    ports:
      - 5001:5432
      
  webapi:
    image: jonathanvmgms/apipostgres6to7ma
    restart: always
    environment:
      - ConnectionStrings__gestionusuarios_db=Server=db;Database=gestionusuarios;Username=postgres;Password=pass123
    ports:
      - 5000:5000
    depends_on:
      - db
