services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
    ports:
      - 6000:5432

  webapi:
    image: gestionusuarios
    restart: always
    environment:
      - ConnectionStrings__gestionusuarios_db=Server=db;Database=gestionusuarios;Username=postgres;Password=pass123
    ports:
      - 5000:5000
    depends_on:
      - db
